name: get_x_master
description: "Independent Flutter state management, routing, and DI solution inspired by GetX with high performance."
version: 0.0.21
homepage: "https://github.com/SwanFlutter/get_x_master"
repository: "https://github.com/SwanFlutter/get_x_master"
issue_tracker: "https://github.com/SwanFlutter/get_x_master/issues"
documentation: "https://github.com/SwanFlutter/get_x_master#readme"

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  intl: ^0.20.2
  shamsi_date: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

    uses-material-design: true
